### ISSUE TITLE
"Failed to parse webhook URL" when using webhook inside thread

### ISSUE THREAD

**Issue by hatkidchan** [Selicre/mc-discord-bridge#13]
I was planning to bridge messages into a thread instead of separate channel using `https://discord.com/api/webhooks/${channel_id}/${token}?thread_id=${thread_id}` link, but it failed to start server with the following exception:

```
java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:91) ~[club_minnced_discord-webhooks-0.8.0-dc09cb6c679ee182.jar:?]
        at selic.re.discordbridge.DiscordBotImpl.<init>(DiscordBotImpl.java:112) ~[mc-discord-bridge-1.1.0.jar:?]
        at selic.re.discordbridge.DiscordBotImpl.init(DiscordBotImpl.java:96) ~[mc-discord-bridge-1.1.0.jar:?]
        at selic.re.discordbridge.DiscordBridgeMod.lambda$onInitialize$0(DiscordBridgeMod.java:26) ~[mc-discord-bridge-1.1.0.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.1.0+cc71601c60-fb62bc0ac5c73e17.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdp000$beforeSetupServer(MinecraftServer.java:3307) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

```

**Comment by Selicre** [comment]
Unfortunately, threads are not yet supported. We'd have to look into that first.
